name: C++ build and release

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - name: Clean build directory
        run: |
          rm -rf build
          mkdir -p build
          
      - name: Configure CMake with version
        run: |
          echo "Setting PROJECT_VERSION to: 1.0.${{ github.run_number }}"
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPROJECT_VERSION="1.0.${{ github.run_number }}"
          
      - name: Debug CMake configuration
        run: |
          echo "=== Current directory ==="
          pwd
          ls -la
          echo "=== Build directory content ==="
          ls -la build/
          echo "=== CMakeCache.txt content ==="
          grep PROJECT_VERSION build/CMakeCache.txt || echo "PROJECT_VERSION not found in cache"
          
      - name: Build project
        run: cmake --build build --config Release
        
      - name: Verify version in binary
        run: |
          echo "=== Binary strings analysis ==="
          strings build/hello_world | grep -i "1.0\|version" | head -20 || echo "No version strings found"
          
      - uses: actions/upload-artifact@v4
        with:
          name: hello-world-ubuntu
          path: build/hello_world

  build-windows:
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v4
      
      - name: Clean build directory
        run: |
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path build -Force
          
      - name: Configure CMake with version
        run: |
          echo "Setting PROJECT_VERSION to: 1.0.${{ github.run_number }}"
          cmake -B build -DPROJECT_VERSION="1.0.${{ github.run_number }}"
          
      - name: Debug CMake configuration
        run: |
          echo "=== Current directory ==="
          Get-Location
          Get-ChildItem
          echo "=== Build directory content ==="
          Get-ChildItem build/
          echo "=== CMakeCache.txt content ==="
          Get-Content build/CMakeCache.txt | Select-String "PROJECT_VERSION" || echo "PROJECT_VERSION not found in cache"
          
      - name: Build project
        run: cmake --build build --config Release
        
      - name: Verify version in binary
        run: |
          echo "=== Binary strings analysis ==="
          strings build/Release/hello_world.exe | Select-String -Pattern "1.0|version" | Select-Object -First 10 || echo "No version strings found"
          
      - uses: actions/upload-artifact@v4
        with:
          name: hello-world-windows
          path: build/Release/hello_world.exe

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows]
    if: github.ref == 'refs/heads/main' 
    
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: List downloaded files
        run: |
          echo "=== Artifacts structure ==="
          ls -la ./artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/hello-world-ubuntu/hello_world
            ./artifacts/hello-world-windows/hello_world.exe
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: Автоматический релиз сборки №${{ github.run_number }}